Traceback (most recent call last):
  File "train_medical_image_based_hargnet.py", line 31, in <module>
    import wandb
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/__init__.py", line 7, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 30, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/apis/__init__.py", line 32, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/apis/internal.py", line 1, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 33, in <module>
    from ..lib.git import GitRepo
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/lib/git.py", line 197, in <module>
    from git import Repo, exc  # type: ignore
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/git/__init__.py", line 42, in <module>
    from git.config import GitConfigParser  # @NoMove @IgnorePep8
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/git/config.py", line 25, in <module>
    from git.util import LockFile
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/git/util.py", line 444, in <module>
    class RemoteProgress(object):
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/git/util.py", line 586, in RemoteProgress
    message: str = '',) -> None:
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/typing.py", line 251, in inner
    return cached(*args, **kwds)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/typing.py", line 351, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/typing.py", line 351, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/typing.py", line 131, in _type_check
    if isinstance(arg, str):
KeyboardInterrupt
Traceback (most recent call last):
  File "train_medical_image_use_self_supervised.py", line 31, in <module>
    import wandb
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 31, in <module>
    from .backend.backend import Backend
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 23, in <module>
    from ..internal.internal import wandb_internal
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 35, in <module>
    from . import sender
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 24, in <module>
    from wandb.filesync.dir_watcher import DirWatcher
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/filesync/dir_watcher.py", line 11, in <module>
    wd_polling = util.vendor_import("watchdog.observers.polling")
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/util.py", line 275, in vendor_import
    module = import_module(name)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/vendor/watchdog/observers/__init__.py", line 63, in <module>
    from .inotify import InotifyObserver as Observer
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/vendor/watchdog/observers/inotify.py", line 74, in <module>
    from .inotify_buffer import InotifyBuffer
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/vendor/watchdog/observers/inotify_buffer.py", line 20, in <module>
    from watchdog.observers.inotify_c import Inotify
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/vendor/watchdog/observers/inotify_c.py", line 62, in <module>
    libc = _load_libc()
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/vendor/watchdog/observers/inotify_c.py", line 34, in _load_libc
    libc_path = ctypes.util.find_library('c')
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/ctypes/util.py", line 350, in find_library
    _findSoname_ldconfig(name) or \
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/ctypes/util.py", line 294, in _findSoname_ldconfig
    env={'LC_ALL': 'C', 'LANG': 'C'}) as p:
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
KeyboardInterrupt
wandb: Currently logged in as: haiduonghust (use `wandb login --relogin` to force relogin)
wandb: Appending key for api.wandb.ai to your netrc file: /home/asilla/.netrc
Problem at: train_medical_image_use_self_supervised.py 37 <module>
Traceback (most recent call last):
  File "train_medical_image_use_self_supervised.py", line 37, in <module>
    wandb.init(project = "Medical Image Deeplabv3+ use pretrained self supervised")
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 976, in init
    raise e
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 623, in init
    run._on_init()
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1761, in _on_init
    current_version=wandb.__version__
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 92, in communicate_check_version
    ret = self._communicate_check_version(check_version)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 422, in _communicate_check_version
    result = self._communicate(rec)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "train_medical_image_segformer.py", line 10, in <module>
    import torch
  File "/home/asilla/anaconda3/envs/duongnh/lib/python3.7/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: KeyboardInterrupt: 
